### ISSUE TITLE
Read only variable

### ISSUE THREAD

**Issue by rossbocc** [MrcJkb/mtype340#1]
Hi Marc,
I do not manage to run the model. I get the following error:

" You cannot set the read-only property 'UA_h' of mtype340 ".

Could you help me? 

Thank you in advanced :)

**Comment by mrcjkb** [comment]
Have you tried the [example script](https://github.com/MrcJkb/mtype340/blob/master/example_script_mtype340.m)?
In the `mtype340` class, `UA_h` is an `immutable` property. Thus, it can only be set once (via the constructor). If you want to change the property, you have to instantiate a new instance of the class.

Best regards,
Marc

**Comment by rossbocc** [comment]
The thing is that I am not changing it. I am just running the script as it is.
Here the error 👍 


![image](https://user-images.githubusercontent.com/72405700/95420772-627d5200-093c-11eb-8cca-fca1290f10a0.png)


Let me know how I could fix it

**Comment by mrcjkb** [comment]
It appears the example script was for an older version of the class.
I have made some adjustments to make them compatible. You can test the changes on the branch [bugfix/issue#1](https://github.com/MrcJkb/mtype340/tree/bugfix/issue%231).

Please let me know if the branch resolves the issue for you and then I will merge it.

**Comment by rossbocc** [comment]
Yes, it does! Just to be sure, I post here the results that  I get after running the script:

![image](https://user-images.githubusercontent.com/72405700/95435188-92375480-0952-11eb-8bfd-32bda170c167.png)

**Comment by mrcjkb** [comment]
Great. That's what it's supposed to look like.

**Comment by rossbocc** [comment]
Thank you a lot :)
